// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.81.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'ffi.io.dart' if (dart.library.html) 'ffi.web.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

part 'bridge_definitions.freezed.dart';

abstract class Native {
  Future<WorldManager> createWorldManager({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateWorldManagerConstMeta;

  Future<int> whatIsTheAnswer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWhatIsTheAnswerConstMeta;

  Future<void> addBlockMethodWorldManager({required WorldManager that, required GlobalBlockPosition position, required String block, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAddBlockMethodWorldManagerConstMeta;

  Future<void> removeBlockMethodWorldManager({required WorldManager that, required GlobalBlockPosition position, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRemoveBlockMethodWorldManagerConstMeta;

  Future<void> addEntityMethodWorldManager({required WorldManager that, required String entity, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAddEntityMethodWorldManagerConstMeta;

  Future<int> entitiesMethodWorldManager({required WorldManager that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitiesMethodWorldManagerConstMeta;

  Stream<NativeMessage> createMessageStreamMethodWorldManager({required WorldManager that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateMessageStreamMethodWorldManagerConstMeta;

  Future<void> closeMethodWorldManager({required WorldManager that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCloseMethodWorldManagerConstMeta;

  Future<GlobalEntityPosition> playerPositionMethodWorldManager({required WorldManager that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPlayerPositionMethodWorldManagerConstMeta;

  Future<void> movePlayerMethodWorldManager({required WorldManager that, double? x, double? y, double? z, bool? relative, bool? teleport, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMovePlayerMethodWorldManagerConstMeta;

  Future<bool> playerOnGroundMethodWorldManager({required WorldManager that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPlayerOnGroundMethodWorldManagerConstMeta;

  DropFnType get dropOpaqueMutexPlayer;
  ShareFnType get shareOpaqueMutexPlayer;
  OpaqueTypeFinalizer get MutexPlayerFinalizer;

  DropFnType get dropOpaqueMutexWorld;
  ShareFnType get shareOpaqueMutexWorld;
  OpaqueTypeFinalizer get MutexWorldFinalizer;

  DropFnType get dropOpaqueMutexWorldMessenger;
  ShareFnType get shareOpaqueMutexWorldMessenger;
  OpaqueTypeFinalizer get MutexWorldMessengerFinalizer;

  DropFnType get dropOpaqueMutexWorldTicker;
  ShareFnType get shareOpaqueMutexWorldTicker;
  OpaqueTypeFinalizer get MutexWorldTickerFinalizer;
}

@sealed
class MutexPlayer extends FrbOpaque {
  MutexPlayer.fromRaw(
    int ptr,
    int size,
  ) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => api.dropOpaqueMutexPlayer;

  @override
  ShareFnType get shareFn => api.shareOpaqueMutexPlayer;

  @override
  OpaqueTypeFinalizer get staticFinalizer => api.MutexPlayerFinalizer;
}

@sealed
class MutexWorld extends FrbOpaque {
  MutexWorld.fromRaw(
    int ptr,
    int size,
  ) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => api.dropOpaqueMutexWorld;

  @override
  ShareFnType get shareFn => api.shareOpaqueMutexWorld;

  @override
  OpaqueTypeFinalizer get staticFinalizer => api.MutexWorldFinalizer;
}

@sealed
class MutexWorldMessenger extends FrbOpaque {
  MutexWorldMessenger.fromRaw(
    int ptr,
    int size,
  ) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => api.dropOpaqueMutexWorldMessenger;

  @override
  ShareFnType get shareFn => api.shareOpaqueMutexWorldMessenger;

  @override
  OpaqueTypeFinalizer get staticFinalizer => api.MutexWorldMessengerFinalizer;
}

@sealed
class MutexWorldTicker extends FrbOpaque {
  MutexWorldTicker.fromRaw(
    int ptr,
    int size,
  ) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => api.dropOpaqueMutexWorldTicker;

  @override
  ShareFnType get shareFn => api.shareOpaqueMutexWorldTicker;

  @override
  OpaqueTypeFinalizer get staticFinalizer => api.MutexWorldTickerFinalizer;
}

class BlockInformation {
  final String name;
  final BlockPosition position;

  const BlockInformation({
    required this.name,
    required this.position,
  });
}

class BlockPosition {
  final int field0;
  final int field1;
  final int field2;

  const BlockPosition({
    required this.field0,
    required this.field1,
    required this.field2,
  });
}

class ChunkLocation {
  final int field0;
  final int field1;
  final int field2;

  const ChunkLocation({
    required this.field0,
    required this.field1,
    required this.field2,
  });
}

class EntityPosition {
  final double field0;
  final double field1;
  final double field2;

  const EntityPosition({
    required this.field0,
    required this.field1,
    required this.field2,
  });
}

class GlobalBlockPosition {
  final ChunkLocation field0;
  final BlockPosition field1;

  const GlobalBlockPosition({
    required this.field0,
    required this.field1,
  });
}

class GlobalEntityPosition {
  final ChunkLocation field0;
  final EntityPosition field1;

  const GlobalEntityPosition({
    required this.field0,
    required this.field1,
  });
}

@freezed
sealed class NativeMessage with _$NativeMessage {
  const factory NativeMessage.addBlock({
    required ChunkLocation chunk,
    required BlockInformation block,
  }) = NativeMessage_AddBlock;
  const factory NativeMessage.removeBlock({
    required BlockPosition position,
    required ChunkLocation chunk,
  }) = NativeMessage_RemoveBlock;
  const factory NativeMessage.addChunk({
    required ChunkLocation location,
    required List<BlockInformation> blocks,
  }) = NativeMessage_AddChunk;
  const factory NativeMessage.removeChunk({
    required ChunkLocation location,
  }) = NativeMessage_RemoveChunk;
  const factory NativeMessage.playerTeleported({
    required double x,
    required double y,
    required double z,
  }) = NativeMessage_PlayerTeleported;
}

class WorldManager {
  final MutexWorld world;
  final MutexWorldMessenger messenger;
  final MutexPlayer player;
  final MutexWorldTicker updateThread;

  const WorldManager({
    required this.world,
    required this.messenger,
    required this.player,
    required this.updateThread,
  });

  Future<void> addBlock({required GlobalBlockPosition position, required String block, dynamic hint}) => api.addBlockMethodWorldManager(
        that: this,
        position: position,
        block: block,
      );

  Future<void> removeBlock({required GlobalBlockPosition position, dynamic hint}) => api.removeBlockMethodWorldManager(
        that: this,
        position: position,
      );

  Future<void> addEntity({required String entity, dynamic hint}) => api.addEntityMethodWorldManager(
        that: this,
        entity: entity,
      );

  Future<int> entities({dynamic hint}) => api.entitiesMethodWorldManager(
        that: this,
      );

  Stream<NativeMessage> createMessageStream({dynamic hint}) => api.createMessageStreamMethodWorldManager(
        that: this,
      );

  Future<void> close({dynamic hint}) => api.closeMethodWorldManager(
        that: this,
      );

  Future<GlobalEntityPosition> playerPosition({dynamic hint}) => api.playerPositionMethodWorldManager(
        that: this,
      );

  Future<void> movePlayer({double? x, double? y, double? z, bool? relative, bool? teleport, dynamic hint}) => api.movePlayerMethodWorldManager(
        that: this,
        x: x,
        y: y,
        z: z,
        relative: relative,
        teleport: teleport,
      );

  Future<bool> playerOnGround({dynamic hint}) => api.playerOnGroundMethodWorldManager(
        that: this,
      );
}
